# Generated by Django 4.1.1 on 2022-09-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="cover_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/cover_photo"
            ),
        ),
    ]
